services:
  user_service:
    build: ./user_service
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"

  payment_service:
    build: ./payment_service
    ports:
      - "5001:5001"
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"

