services:
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - microservices_net
    depends_on:
      - mysql_db

  payment_service:
    build:
      context: ./payment_service
    container_name: payment_service
    ports:
      - "3000:3000"
    networks:
      - microservices_net
    depends_on:
      - mongo_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - microservices_net
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_db:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - microservices_net
    volumes:
      - mongo_data:/data/db

networks:
  microservices_net:

volumes:
  mysql_data:
  mongo_data:
