services:

  user_view:
    build:
      context: ./user_view
    container_name: user_view
    ports:
      - "5001:5001"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_NAME=user_service_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - FLASK_ENV=development
    networks:
      - microservices_net



  user_add:
    build:
      context: ./user_add
    container_name: user_add
    ports:
      - "5000:5000"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_NAME=user_service_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - FLASK_ENV=development
    networks:
      - microservices_net

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service_db 
    ports:
      - "3306:3306"
    networks:
      - microservices_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  payment_service:
    build:
      context: ./payment_service
    container_name: payment_service
    ports:
      - "3000:3000"
    networks:
      - microservices_net

networks:
  microservices_net:



