apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  # Common environment variables
  DB_HOST: mysql-db
  DB_PORT: {{ .Values.mysql_db.port | quote }}
  DB_NAME:  {{ .Values.mysql_db.MYSQL_DATABASE }}
  DB_USER: {{ .Values.mysql_db.MYSQL_USER }}
  DB_PASSWORD: {{ .Values.mysql_db.MYSQL_ROOT_PASSWORD }}
  FLASK_ENV: development
