apiVersion: v1
kind: Service
metadata:
  name: payment-service-service
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: {{ .Values.payment_service.port }}
    targetPort: {{ .Values.payment_service.port }}
  type: {{ .Values.service_type }}
