apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-add-deployment
  labels:
    app: user-add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-add
  template:
    metadata:
      labels:
        app: user-add
    spec:
      containers:
      - name: user-add
        image: {{ .Values.user_add.image }}
        ports:
        - containerPort: {{ .Values.user_add.port }}
        envFrom:
        - configMapRef:
            name: microservices-config