apiVersion: v1
kind: Service
metadata:
  name: user-view-service
spec:
  selector:
    app: user-view
  ports:
  - protocol: TCP
    port: {{ .Values.user_view.port }}
    targetPort: {{ .Values.user_view.port }}
  type: {{ .Values.service_type }}
