apiVersion: v1
kind: Service
metadata:
  name: user-add-service
spec:
  selector:
    app: user-add
  ports:
  - protocol: TCP
    port: {{ .Values.user_add.port }}
    targetPort: {{ .Values.user_add.port }}
  type: {{ .Values.service_type }}
