pipeline {
    agent any
    environment {
        // Define the full path of the micro service project inside the project
        USER_SERVICE_DIR = 'payment_service'
    }
    stages {
        stage('Print Message') {
            steps {
                echo 'Hello im From Shons MicroservicesApp Project!'
            }
        }

        stage('Checkout') {
            steps {
                // Checkout the repository
                checkout scm
            }
        }

        stage('Build Docker Image for payment_service') {
            steps {
                script {
                    dir("${env.USER_SERVICE_DIR}") {
                        sh 'docker build -t shonnahum/microservices:payment_services .'
                    }
                }
            }
        }
        stage('Push Docker Image to DockerHub') {
            steps {
                script {
                    withDockerRegistry([credentialsId: 'docker-hub-credentials	', url: 'https://index.docker.io/v1/']) {
                        sh 'docker push shonnahum/microservices:payment_service'
                    }
                }
            }
        }

    }

}
