services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"     
      - "50000:50000"     # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/jenkins_ssh:/var/jenkins_home/.ssh/id_rsa
      - ~/.ssh/jenkins_ssh.pub:/var/jenkins_home/.ssh/id_rsa.pub
      - ~/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - GIT_SSH_COMMAND=ssh -i /var/jenkins_home/.ssh/id_rsa



volumes:
  jenkins_home:
