pipeline {
    agent any
    environment {
        // Define the full path of the micro service project inside the project
        USER_SERVICE_DIR = 'MicroservicesApp/user_view'
    }
    stages {
        stage('Print Message') {
            steps {
                echo 'Hello im From Shons MicroservicesApp Project!'
            }
        }

        stage('Checkout') {
            steps {
                // Checkout the repository
                checkout scm
            }
        }

        stage('Build Docker Image for user_service') {
            steps {
                script {
                    // Change to the project/user_service directory
                    dir("${env.USER_SERVICE_DIR}") {
                        // Build the Docker image using the Dockerfile inside the user_service folder
                        sh 'docker build -t user_view_image_from_Jenkins .'
                    }
                }
            }
        }

    }

}
