apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  # Common environment variables
  DB_HOST: mysql-db
  DB_PORT: "3306"
  DB_NAME: user_service_db
  DB_USER: root
  DB_PASSWORD: rootpassword
  FLASK_ENV: development
