apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-view-deployment
  labels:
    app: user-view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-view
  template:
    metadata:
      labels:
        app: user-view
    spec:
      containers:
      - name: user-view
        image: shonnahum/microservices:user_view
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: microservices-config